# Generated by Django 4.1.4 on 2023-01-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_project_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.priority'),
        ),
    ]
