# Generated by Django 4.1.4 on 2023-01-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_priority_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
