# Generated by Django 4.1.4 on 2023-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_task_priority_level_delete_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('Z', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='priority_level',
        ),
    ]
