# Generated by Django 4.1.4 on 2023-01-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.IntegerField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='2'),
        ),
    ]
