# Generated by Django 4.1.4 on 2023-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('C', 'Low'), ('B', 'Medium'), ('A', 'High')], default='B', max_length=1),
        ),
    ]
